/* _core.c — C extension: XXTEA decrypt + embedded encrypted flag.
   Only this function is exposed to Python. The flag bytes never appear in .pyc.

   Build: python setup.py build_ext --inplace
   (or use `uv run python setup.py build_ext --inplace`)
*/

#define PY_SSIZE_T_CLEAN
#include <Python.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>

#define DELTA 0x9E3779B9

/* ── XXTEA ────────────────────────────────────────────────── */

static uint32_t mx(uint32_t z, uint32_t y, uint32_t total,
                   const uint32_t key[4], int p, int e) {
    return ((z >> 5 ^ y << 2) + (y >> 3 ^ z << 4))
         ^ ((total ^ y) + (key[(p & 3) ^ e] ^ z));
}

static void xxtea_decrypt(uint32_t *v, int n, const uint32_t key[4]) {
    if (n < 2) return;
    int q = 6 + 52 / n;
    uint32_t total = (uint32_t)(DELTA * q);
    uint32_t y = v[0];
    int rounds = q;
    while (rounds-- > 0) {
        int e = (total >> 2) & 3;
        int p;
        for (p = n - 1; p > 0; p--) {
            uint32_t z = v[p - 1];
            v[p] -= mx(z, y, total, key, p, e);
            y = v[p];
        }
        uint32_t z = v[n - 1];
        v[0] -= mx(z, y, total, key, 0, e);
        y = v[0];
        total -= DELTA;
    }
}

/* ── embedded encrypted flag ───────────────────────────────── */

/* Generated by gen_flag.py — copy the hex here after each flag update. */
static const unsigned char ENCRYPTED_FLAG[] = {
    0xd4, 0xd8, 0xe1, 0x53, 0x38, 0x70, 0xe0, 0x9c,
    0x9d, 0x75, 0x3c, 0xc9, 0x01, 0x13, 0xbd, 0x58,
    0xe3, 0xb6, 0x22, 0x4d, 0x17, 0x42, 0x13, 0x7c,
    0x1f, 0x1a, 0x83, 0x2c, 0x85, 0x44, 0x78, 0xd1
};
static const size_t FLAG_LEN = sizeof(ENCRYPTED_FLAG);

/* ── Python callable ───────────────────────────────────────── */

static PyObject *decrypt_flag(PyObject *self, PyObject *args) {
    const unsigned char *key_bytes;
    Py_ssize_t key_len;

    if (!PyArg_ParseTuple(args, "y#", &key_bytes, &key_len))
        return NULL;

    if (key_len < 16) {
        PyErr_SetString(PyExc_ValueError, "key must be at least 16 bytes");
        return NULL;
    }

    /* Copy encrypted data (XXTEA works on uint32 arrays in-place) */
    int n = (int)(FLAG_LEN / 4);
    uint32_t *v = (uint32_t *)malloc((size_t)n * sizeof(uint32_t));
    if (!v) return PyErr_NoMemory();
    memcpy(v, ENCRYPTED_FLAG, FLAG_LEN);

    /* Key: first 16 bytes as 4 x uint32 little-endian */
    uint32_t k[4];
    memcpy(k, key_bytes, 16);

    xxtea_decrypt(v, n, k);

    /* Convert back to bytes */
    unsigned char *out = (unsigned char *)v;
    /* Strip trailing null bytes (XXTEA padding) */
    Py_ssize_t out_len = (Py_ssize_t)FLAG_LEN;
    while (out_len > 0 && out[out_len - 1] == 0)
        out_len--;

    PyObject *result = PyUnicode_DecodeUTF8((const char *)out, out_len, NULL);
    free(v);
    return result;
}

static PyMethodDef methods[] = {
    {"decrypt", decrypt_flag, METH_VARARGS,
     "decrypt(key_bytes) -> flag_string\n\n"
     "Decrypt the embedded flag using XXTEA with a 16-byte key."},
    {NULL, NULL, 0, NULL}
};

static struct PyModuleDef module = {
    PyModuleDef_HEAD_INIT,
    "_core",
    "XXTEA flag decryption — keep flag bytes out of .pyc",
    -1,
    methods
};

PyMODINIT_FUNC PyInit__core(void) {
    return PyModule_Create(&module);
}
